export const CONSTANTS = {
  EMAIL: 'Email',
  PASSWORD: 'Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  LOGIN: 'Login',
  REGISTRATION: 'Registration',
  USERNAME: 'User_Name',
  MOBILENO: 'Mobile_No',
  TITLE: 'Title',
  ABOUT: 'About',
  POST: 'Post',
  READ_MORE: 'Read More',
  Have_Login: 'Have_Account_Login?',
  Dont_Have_Account: 'Dont_Have_Account_SignUp?',
};
